"""Compile checked-in shaders; embed portable Vulkan 1.0 SPIR-V as uint32 arrays."""
import argparse
from pathlib import Path
import shutil
import struct
import subprocess

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output', type=Path, default=root/'build/generated')
out = parser.parse_args().output
out.mkdir(parents=True, exist_ok=True)
compiler = shutil.which('glslangValidator')
if not compiler:
    raise SystemExit('glslangValidator is required to compile Vulkan shaders')
header = ['/* Generated by tools/build_shaders.py. */', '#include <stdint.h>']
for source,symbol in [('sprite.vert','vert'),('sprite.frag','frag'),('lit.vert','lit_vert'),('lit.frag','lit_frag'),('skin.comp','skin_comp'),('transfer.comp','transfer_comp')]:
    target = out / f'{source}.spv'
    subprocess.run([compiler,'-V','--target-env','vulkan1.0',str(root/'runtime/render/shaders'/source),'-o',str(target)],check=True)
    validator = shutil.which('spirv-val')
    if validator:
        subprocess.run([validator,'--target-env','vulkan1.0',str(target)],check=True)
    data = target.read_bytes()
    words = struct.unpack('<'+'I'*(len(data)//4),data)
    header.append(f'static const uint32_t bk_{symbol}_spv[] = {{')
    for pos in range(0,len(words),8):
        header.append('    '+','.join(f'0x{v:08x}u' for v in words[pos:pos+8])+',')
    header.append('};')
(out/'shaders.h').write_text('\n'.join(header)+'\n')
