"""Bake the small fixed Japanese control legend, not a runtime font dependency.

Input: Noto Sans CJK JP Regular (Sans2.004), licensed under SIL OFL1.1.
Download URL and upstream SHA256 are recorded in the generated header.
Pillow is needed only when changing legend text and regenerating the atlas.
"""
import argparse
import ast
import hashlib
import math
from pathlib import Path
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'https://github.com/notofonts/noto-cjk/blob/main/Sans/OTF/Japanese/NotoSansCJKjp-Regular.otf'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('font', type=Path)
    args = parser.parse_args()
    source = (ROOT/'runtime/scene/control_help.c').read_text()
    body = source.split('pages[BK_HELP_COUNT] = {', 1)[1].split('\n};', 1)[0]
    strings = [ast.literal_eval(s) for s in re.findall(r'"(?:[^"\\]|\\.)*"', body)]
    chars = sorted(set(''.join(strings)) - {'\n', '\t'})
    font = ImageFont.truetype(str(args.font), 16)
    cell = 22
    rows = (len(chars)+15)//16
    output = ['/* Generated by tools/generate_control_help_font.py. Do not edit.',
              ' * Noto Sans CJK JP raster subset; SIL OFL1.1: licenses/NotoSansCJK-OFL.txt.',
              ' * Source: '+SOURCE,
              ' * Font SHA256: '+hashlib.sha256(args.font.read_bytes()).hexdigest()+' */',
              '#ifndef BK_UI_CONTROL_HELP_FONT_H', '#define BK_UI_CONTROL_HELP_FONT_H',
              '#include <stdint.h>',
              f'enum {{ BK_HELP_CELL={cell}, BK_HELP_COLUMNS=16, BK_HELP_ROWS={rows}, BK_HELP_GLYPHS={len(chars)} }};',
              'static const struct { uint32_t codepoint; uint8_t advance; uint8_t mask[BK_HELP_CELL*BK_HELP_CELL/2]; } bk_help_glyphs[BK_HELP_GLYPHS] = {']
    for char in chars:
        image = Image.new('L', (cell,cell))
        ImageDraw.Draw(image).text((1,18),char,font=font,fill=255,anchor='ls')
        pixels = [round(v/17) for v in image.tobytes()]
        packed = [(pixels[i]<<4)|pixels[i+1] for i in range(0,len(pixels),2)]
        advance = math.ceil(font.getlength(char))
        output.append(f'  {{0x{ord(char):04x},{advance},{{'+','.join(f'0x{v:02x}' for v in packed)+'}},')
    output += ['};', '#endif', '']
    (ROOT/'runtime/ui/control_help_font.h').write_text('\n'.join(output))
    for text in strings:
        for line in text.splitlines():
            width = sum(math.ceil(font.getlength(c)) for c in line if c!='\t')
            if width>136: raise ValueError(f'Legend line too wide ({width}): {line}')
    print(f'Generated {len(chars)} glyphs; {cell*cell//2*len(chars)} packed mask bytes')

if __name__ == '__main__': main()
