set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(BK_SWITCH ON CACHE BOOL "Build for Nintendo Switch" FORCE)
if(NOT DEFINED DEVKITPRO)
  if(DEFINED ENV{DEVKITPRO})
    set(DEVKITPRO "$ENV{DEVKITPRO}" CACHE PATH "devkitPro root")
  else()
    set(DEVKITPRO "/opt/devkitpro" CACHE PATH "devkitPro root")
  endif()
endif()
set(CMAKE_C_COMPILER "${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-gcc")
set(CMAKE_AR "${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-ar")
set(CMAKE_RANLIB "${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-ranlib")
set(CMAKE_NM "${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-nm")
set(CMAKE_C_FLAGS_INIT "-D__SWITCH__ -DBK_ARM64_FAST -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-specs=${DEVKITPRO}/libnx/switch.specs")
